import { TemplatePartsMapper } from "../../src/templates/templatePartsMapper";
import { TemplateMap } from "../../src/templates/types";
import * as path from "path";
import * as fs from "fs";

/**
 * Template Parts Mapper Tests
 *
 * These tests validate the EXACT order and structure of template parts maps
 * generated by TemplatePartsMapper.
 * They ensure that includes are resolved in the correct order and files are
 * split properly when they contain includes.
 *
 * Expected orders are based on the output of: node out/debugScripts/listAllTemplatePartsMaps.js
 */

const fixturesPath = path.resolve(__dirname, "../../fixtures/market-repo");

interface ExpectedPart {
  file: string; // basename of the file
  startLine: number;
  endLine: number;
}

function validateTemplateParts(
  result: TemplateMap | null,
  expectedParts: ExpectedPart[],
  templateName: string,
) {
  expect(result).not.toBeNull();
  if (!result) return;

  expect(result).toBeDefined();
  expect(templateName).toBeDefined(); // to avoid unused variable warning

  const partSections = result.partSections;
  expect(partSections.length).toBe(expectedParts.length);

  // Validate involvedFiles exists and is an array
  expect(result.involvedFiles).toBeDefined();
  expect(Array.isArray(result.involvedFiles)).toBe(true);

  // Validate that involvedFiles contains unique files
  const uniqueFiles = new Set(result.involvedFiles);
  expect(uniqueFiles.size).toBe(result.involvedFiles.length);

  // Validate each part in exact order
  expectedParts.forEach((expectedPart, index) => {
    const actualPart = partSections[index];
    const actualFilename = path.basename(actualPart.fileFullPath);

    expect(actualFilename).toBe(expectedPart.file);
    expect(actualPart.startLine).toBe(expectedPart.startLine);
    expect(actualPart.endLine).toBe(expectedPart.endLine);

    // Verify file exists
    expect(fs.existsSync(actualPart.fileFullPath)).toBe(true);

    // Verify file is in involvedFiles list
    expect(result.involvedFiles).toContain(actualPart.fileFullPath);
  });
}

describe("TemplatePartsMapper - Order Validation", () => {
  let mapper: TemplatePartsMapper;

  beforeAll(() => {
    mapper = new TemplatePartsMapper(fixturesPath);
  });

  describe("Reconciliation Texts", () => {
    it("reconciliation_text_1: should have exact part order", () => {
      const result = mapper.generateTemplateMap(
        "reconciliationText",
        "reconciliation_text_1",
      );

      const expectedParts: ExpectedPart[] = [
        { file: "main.liquid", startLine: 0, endLine: 3 },
        { file: "part_1.liquid", startLine: 0, endLine: 1 },
        { file: "part_2.liquid", startLine: 0, endLine: 2 },
        { file: "part_1.liquid", startLine: 3, endLine: 8 },
        { file: "shared_part_1.liquid", startLine: 0, endLine: 1 },
        { file: "part_1.liquid", startLine: 10, endLine: 13 },
        { file: "main.liquid", startLine: 5, endLine: 13 },
      ];

      validateTemplateParts(result, expectedParts, "reconciliation_text_1");
    });

    it("reconciliation_text_2: should have exact part order", () => {
      const result = mapper.generateTemplateMap(
        "reconciliationText",
        "reconciliation_text_2",
      );

      const expectedParts: ExpectedPart[] = [
        { file: "shared_part_1.liquid", startLine: 0, endLine: 1 },
        { file: "shared_part_2.liquid", startLine: 0, endLine: 1 },
        { file: "variable_shared.liquid", startLine: 0, endLine: 7 },
        { file: "main.liquid", startLine: 3, endLine: 9 },
      ];

      validateTemplateParts(result, expectedParts, "reconciliation_text_2");
    });

    it("reconciliation_text_3: should have exact part order with complex includes", () => {
      const result = mapper.generateTemplateMap(
        "reconciliationText",
        "reconciliation_text_3",
      );

      const expectedParts: ExpectedPart[] = [
        { file: "part_1.liquid", startLine: 0, endLine: 2 },
        { file: "main.liquid", startLine: 1, endLine: 7 },
        { file: "part_2.liquid", startLine: 0, endLine: 3 },
        { file: "part_3.liquid", startLine: 0, endLine: 1 },
        { file: "part_4.liquid", startLine: 0, endLine: 1 },
        { file: "part_2.liquid", startLine: 6, endLine: 7 },
        { file: "main.liquid", startLine: 9, endLine: 9 },
      ];

      validateTemplateParts(result, expectedParts, "reconciliation_text_3");
    });

    it("variable_definition_test: should have exact part order", () => {
      const result = mapper.generateTemplateMap(
        "reconciliationText",
        "variable_definition_test",
      );

      const expectedParts: ExpectedPart[] = [
        { file: "main.liquid", startLine: 0, endLine: 27 },
        { file: "definitions.liquid", startLine: 0, endLine: 12 },
        { file: "main.liquid", startLine: 29, endLine: 33 },
        { file: "variable_shared.liquid", startLine: 0, endLine: 7 },
        { file: "main.liquid", startLine: 35, endLine: 49 },
      ];

      validateTemplateParts(result, expectedParts, "variable_definition_test");
    });

    it("translation_test: should have exact part order", () => {
      const result = mapper.generateTemplateMap(
        "reconciliationText",
        "translation_test",
      );

      const expectedParts: ExpectedPart[] = [
        { file: "main.liquid", startLine: 0, endLine: 3 },
        { file: "translations_def.liquid", startLine: 0, endLine: 3 },
        { file: "translation_shared.liquid", startLine: 0, endLine: 4 },
        { file: "translations_def.liquid", startLine: 5, endLine: 7 },
        { file: "main.liquid", startLine: 5, endLine: 13 },
      ];

      validateTemplateParts(result, expectedParts, "translation_test");
    });

    it("include_parts_test: should have exact part order with nested includes", () => {
      const result = mapper.generateTemplateMap(
        "reconciliationText",
        "include_parts_test",
      );

      const expectedParts: ExpectedPart[] = [
        { file: "main.liquid", startLine: 0, endLine: 4 },
        { file: "included_1.liquid", startLine: 0, endLine: 2 },
        { file: "included_2.liquid", startLine: 0, endLine: 0 },
        { file: "included_1.liquid", startLine: 4, endLine: 4 },
        { file: "included_shared_2.liquid", startLine: 0, endLine: 0 },
        { file: "included_1.liquid", startLine: 6, endLine: 7 },
        { file: "main.liquid", startLine: 6, endLine: 10 },
        { file: "included_shared_1.liquid", startLine: 0, endLine: 0 },
        { file: "included_shared_2.liquid", startLine: 0, endLine: 0 },
        { file: "included_shared_1.liquid", startLine: 2, endLine: 3 },
        { file: "main.liquid", startLine: 12, endLine: 12 },
        { file: "main.liquid", startLine: 14, endLine: 14 },
      ];

      validateTemplateParts(result, expectedParts, "include_parts_test");
    });

    it("definitions_and_references: single file should have one part", () => {
      const result = mapper.generateTemplateMap(
        "reconciliationText",
        "definitions_and_references",
      );

      const expectedParts: ExpectedPart[] = [
        { file: "main.liquid", startLine: 0, endLine: 155 },
      ];

      validateTemplateParts(
        result,
        expectedParts,
        "definitions_and_references",
      );
    });
  });

  describe("Export Files", () => {
    it("export_1: should have exact part order", () => {
      const result = mapper.generateTemplateMap("exportFile", "export_1");

      const expectedParts: ExpectedPart[] = [
        { file: "part_1.liquid", startLine: 0, endLine: 1 },
        { file: "part_2.liquid", startLine: 0, endLine: 0 },
        { file: "part_1.liquid", startLine: 3, endLine: 3 },
        { file: "main.liquid", startLine: 1, endLine: 4 },
      ];

      validateTemplateParts(result, expectedParts, "export_1");
    });

    it("export_2: single file should have one part", () => {
      const result = mapper.generateTemplateMap("exportFile", "export_2");

      const expectedParts: ExpectedPart[] = [
        { file: "main.liquid", startLine: 0, endLine: 0 },
      ];

      validateTemplateParts(result, expectedParts, "export_2");
    });

    it("export_3: should have exact part order with shared parts", () => {
      const result = mapper.generateTemplateMap("exportFile", "export_3");

      const expectedParts: ExpectedPart[] = [
        { file: "main.liquid", startLine: 0, endLine: 3 },
        { file: "part_1.liquid", startLine: 0, endLine: 1 },
        { file: "shared_part_2.liquid", startLine: 0, endLine: 1 },
        { file: "part_1.liquid", startLine: 3, endLine: 5 },
        { file: "main.liquid", startLine: 5, endLine: 7 },
        { file: "shared_part_3.liquid", startLine: 0, endLine: 0 },
        { file: "shared_part_1.liquid", startLine: 0, endLine: 1 },
        { file: "shared_part_3.liquid", startLine: 2, endLine: 2 },
        { file: "main.liquid", startLine: 9, endLine: 11 },
      ];

      validateTemplateParts(result, expectedParts, "export_3");
    });
  });

  describe("Account Templates", () => {
    it("account_1: should have exact part order", () => {
      const result = mapper.generateTemplateMap("accountTemplate", "account_1");

      const expectedParts: ExpectedPart[] = [
        { file: "part_1.liquid", startLine: 0, endLine: 1 },
        { file: "part_2.liquid", startLine: 0, endLine: 2 },
        { file: "part_1.liquid", startLine: 3, endLine: 3 },
        { file: "main.liquid", startLine: 1, endLine: 4 },
      ];

      validateTemplateParts(result, expectedParts, "account_1");
    });

    it("account_2: should have exact part order", () => {
      const result = mapper.generateTemplateMap("accountTemplate", "account_2");

      const expectedParts: ExpectedPart[] = [
        { file: "main.liquid", startLine: 0, endLine: 1 },
        { file: "part_1.liquid", startLine: 0, endLine: 0 },
      ];

      validateTemplateParts(result, expectedParts, "account_2");
    });

    it("account_3: should have exact part order with complex shared parts", () => {
      const result = mapper.generateTemplateMap("accountTemplate", "account_3");

      const expectedParts: ExpectedPart[] = [
        { file: "main.liquid", startLine: 0, endLine: 1 },
        { file: "shared_part_3.liquid", startLine: 0, endLine: 0 },
        { file: "shared_part_1.liquid", startLine: 0, endLine: 1 },
        { file: "shared_part_3.liquid", startLine: 2, endLine: 2 },
        { file: "main.liquid", startLine: 3, endLine: 3 },
        { file: "part_1.liquid", startLine: 0, endLine: 1 },
        { file: "part_2.liquid", startLine: 0, endLine: 2 },
        { file: "part_1.liquid", startLine: 3, endLine: 4 },
        { file: "main.liquid", startLine: 5, endLine: 5 },
        { file: "shared_part_2.liquid", startLine: 0, endLine: 1 },
        { file: "main.liquid", startLine: 7, endLine: 7 },
      ];

      validateTemplateParts(result, expectedParts, "account_3");
    });
  });

  describe("File Order and Deduplication", () => {
    it("should maintain file order by first appearance in involvedFiles", () => {
      // account_3 has: main -> shared_part_3 -> shared_part_1 -> shared_part_3 (again) -> main (again) -> part_1 -> part_2 -> part_1 (again) -> main (again) -> shared_part_2 -> main (again)
      const result = mapper.generateTemplateMap("accountTemplate", "account_3");

      expect(result).not.toBeNull();
      if (!result) return;

      // involvedFiles should have files in order of first appearance
      const fileBasenames = result.involvedFiles.map((f) => path.basename(f));

      expect(fileBasenames).toEqual([
        "main.liquid", // appears first at index 0
        "shared_part_3.liquid", // appears first at index 1
        "shared_part_1.liquid", // appears first at index 2
        "part_1.liquid", // appears first at index 5
        "part_2.liquid", // appears first at index 6
        "shared_part_2.liquid", // appears first at index 9
      ]);

      // Verify each file appears only once in involvedFiles
      const uniqueFiles = new Set(fileBasenames);
      expect(uniqueFiles.size).toBe(fileBasenames.length);
    });

    it("should deduplicate files that appear multiple times in partSections", () => {
      const result = mapper.generateTemplateMap("accountTemplate", "account_3");

      expect(result).not.toBeNull();
      if (!result) return;

      // Count how many times each file appears in partSections
      const fileCounts = new Map<string, number>();
      for (const section of result.partSections) {
        const basename = path.basename(section.fileFullPath);
        fileCounts.set(basename, (fileCounts.get(basename) || 0) + 1);
      }

      // main.liquid appears 4 times in sections
      expect(fileCounts.get("main.liquid")).toBe(4);
      // shared_part_3.liquid appears 2 times in sections
      expect(fileCounts.get("shared_part_3.liquid")).toBe(2);
      // part_1.liquid appears 2 times in sections
      expect(fileCounts.get("part_1.liquid")).toBe(2);

      // But each should only appear once in involvedFiles
      const involvedFileBasenames = result.involvedFiles.map((f) =>
        path.basename(f),
      );
      expect(
        involvedFileBasenames.filter((f) => f === "main.liquid").length,
      ).toBe(1);
      expect(
        involvedFileBasenames.filter((f) => f === "shared_part_3.liquid")
          .length,
      ).toBe(1);
      expect(
        involvedFileBasenames.filter((f) => f === "part_1.liquid").length,
      ).toBe(1);
    });
  });

  describe("Error Cases", () => {
    it("should return null for non-existent template", () => {
      const result = mapper.generateTemplateMap(
        "reconciliationText",
        "non_existent",
      );

      expect(result).toBeNull();
    });
  });
});
